version: '3'

services:
  nats-streaming:
    image: nats-streaming:latest
    restart: always
    command: -p 4222 -m 8222 -dir data -store file --debug=true --trace=true
    ports:
      - "4222:4222"
      - "8222:8222"
    
    volumes:
      - ./_nats_data:/data
  
  postgres:
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

# volumes:
#   ./db/db-data: